### ISSUE TITLE
Feature request: Add some support for "non interactive" client

### ISSUE THREAD

**Issue by raff** [peterh/liner#32]
I tried to redirect the output of my application to a file and I got an error "standard output is not a terminal" (errNotTerminalOutput) from Prompt()

A couple of options:
- easy one: change errNotTerminalOutput to ErrNotTerminalOutput so I have something to compare against (and I can add some code so that instead of using Prompt() I read a line from stdin.
- still easy: add a method I can call (State.IsTerminalOutput) so I can use it to decide if calling Prompt() or not
- complicated ? have Prompt() support "non terminal output" and do a read line from stdin (that, I think, is what libreadline does).

Thanks!
-- Raffaele

**Comment by peterh** [comment]
Good point.

I think the behaviour should be:
* If stdin is redirected, read the next line without displaying a prompt (regardless of whether stdout is redirected or not)
* If stdin is not redirected, but stdout is, return ErrNotTerminalOutput
* Otherwise, do the normal Prompt thing

Does that sound correct to you?
