### ISSUE TITLE
MultiLineMode on Windows problems

### ISSUE THREAD

**Issue by filimonov** [peterh/liner#98]
- Operating System: Windows 7
- Terminal Emulator: Command Prompt
- Bug behaviour: For multiline mode liner works incorrect if line is wider than screen (misplace the cursor, clear previous lines, etc), please see the gif attached:
![liner_multiline](https://user-images.githubusercontent.com/1549571/34692178-824b27cc-f4bf-11e7-97c4-7b250e9fb232.gif)

- Expected behaviour: correct work in Multiline mode
- Complete sample that reproduces the bug: 
```go
package main
import (
	"log"
	"github.com/peterh/liner"
)
func main() {
	line := liner.NewLiner()
	defer line.Close()

	line.SetMultiLineMode(true)

	if name, err := line.Prompt("What is your name? "); err == nil {
		log.Print("Got: ", name)
	}
}
```

**Comment by filimonov** [comment]
Removing that line fixes the issue
https://github.com/peterh/liner/blob/3681c2a912330352991ecdd642f257efe5b85518/output_windows.go#L74

Why it was added?

**Comment by peterh** [comment]
When input is at the bottom of the screen, and not in multi-line mode, drawing a character at the end of the line causes Windows to scroll everything up (at least in recent versions of Windows). This eventually fills the screen (which is annoying in multi-line mode, and disastrous in the default single-line mode). So we have to leave an extra character for the cursor to 'live' in.

Multi-line mode was contributed by another user. It might need to change to break lines manually instead of trusting the terminal to wrap where it thinks the terminal might wrap. @flisky could you please take a look?

**Comment by filimonov** [comment]
Fixend in #101
